title: "Psychological Drivers of Economic Decision-Making Dataset"
description: "This dataset compiles global evidence on psychological factors that drive economic decision-making, spanning behavioral economics, cognitive psycholog"
author: "Juan Moisés de la Serna Tuya"
url: "https://juanmoisesd.github.io"
baseurl: "/psychological-drivers-of-economic-decision-making-dataset"
